import logging
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional

from motor.motor_asyncio import AsyncIOMotorClient
import voyageai

from nexus_ai.config import get_settings

logger = logging.getLogger(__name__)

class SharedMemoryManager:
    """
    Manages shared memory for agents using MongoDB as a vector store.
    """
    def __init__(self):
        self.settings = get_settings()
        self.mongo_client = AsyncIOMotorClient(self.settings.mongodb_uri)
        self.db = self.mongo_client[self.settings.mongodb_database]
        self.collection = self.db["shared_agent_memories"]
        
        self.voyage_client = None
        if self.settings.voyage_api_key:
            self.voyage_client = voyageai.AsyncClient(api_key=self.settings.voyage_api_key)
        else:
            logger.warning("Voyage API key not set. Shared agent memory embeddings will not work.")

    async def _get_embedding(self, text: str) -> Optional[List[float]]:
        if not self.voyage_client or not text:
            return None
            
        try:
            response = await self.voyage_client.embed(
                texts=[text],
                model="voyage-2"
            )
            return response.embeddings[0]
        except Exception as e:
            logger.error(f"Failed to generate embedding: {e}")
            return None

    async def save_memory(
        self, 
        patient_id: int, 
        source_agent: str, 
        content: str, 
        metadata: Optional[Dict[str, Any]] = None
    ) -> bool:
        """
        Saves a factual constraint or memory generated by an agent.
        """
        embedding = await self._get_embedding(content)
        if not embedding:
            logger.error("Could not generate embedding for memory.")
            return False
            
        memory_doc = {
            "patient_id": patient_id,
            "source_agent": source_agent,
            "content": content,
            "embedding": embedding,
            "metadata": metadata or {},
            "created_at": datetime.now(timezone.utc)
        }
        
        try:
            await self.collection.insert_one(memory_doc)
            return True
        except Exception as e:
            logger.error(f"Failed to save memory to MongoDB: {e}")
            return False

    async def search_memories(
        self, 
        patient_id: int, 
        query: str, 
        limit: int = 5
    ) -> List[Dict[str, Any]]:
        """
        Searches for relevant memories using vector search.
        Requires Atlas Vector Search index on the 'embedding' field.
        """
        embedding = await self._get_embedding(query)
        if not embedding:
            return []
            
        pipeline = [
            {
                "$vectorSearch": {
                    "index": "vector_index",
                    "path": "embedding",
                    "queryVector": embedding,
                    "numCandidates": 50,
                    "limit": limit,
                    "filter": {"patient_id": {"$eq": patient_id}}
                }
            },
            {
                "$project": {
                    "_id": 0,
                    "content": 1,
                    "source_agent": 1,
                    "created_at": 1,
                    "score": {"$meta": "vectorSearchScore"}
                }
            }
        ]
        
        try:
            cursor = self.collection.aggregate(pipeline)
            results = await cursor.to_list(length=limit)
            return results
        except Exception as e:
            logger.error(f"Failed to search memories: {e}")
            # Fallback to no results if index doesn't exist
            return []
